import { createSlice, createAsyncThunk, PayloadAction } from "@reduxjs/toolkit";
import { TradeStrategyBotControlState } from "./BotControlActions";

const initialState: TradeStrategyBotControlState = {
    filter: null,
};

export const botControlSlice = createSlice({
    name: "botControl",
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {},
    // The `extraReducers` field lets the slice handle actions defined elsewhere, including actions generated by createAsyncThunk or in other slices.
    extraReducers: {},
});

export default botControlSlice.reducer;
