import { createSlice, createAsyncThunk, PayloadAction } from "@reduxjs/toolkit";
import { TradeStrategyAnalysisState } from "./AnalysisActions";

export const initialState: TradeStrategyAnalysisState = {
    filter: null,
    shares: [],
    currencies: [],
    futures: [],
    premise: null,
};

export const analysisSlice = createSlice({
    name: "analysis",
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {},
    // The `extraReducers` field lets the slice handle actions defined elsewhere, including actions generated by createAsyncThunk or in other slices.
    extraReducers: {},
});

export default analysisSlice.reducer;
