import {
  createAsyncThunk,
  createSelector,
  createSlice,
  PayloadAction,
} from "@reduxjs/toolkit";
import traderRestApi from "../../common/api/rest/traderRestApi";
import { ActiveTrade } from "../../common/data/ActiveTrade";
import { LoadingState } from "../LoadingState";
import { handleThunkError } from "../reduxUtils";
import { RootState } from "../store";

export interface ActiveTradesState {
  activeTrades: ActiveTrade[];
  activeTradesLoading: LoadingState;
  activeTradesLoadingError?: string;

  selected?: ActiveTrade;
}

export const initialState: ActiveTradesState = {
  activeTrades: [],
  activeTradesLoading: LoadingState.IDLE,
};

export const loadActiveTrades = createAsyncThunk<ActiveTrade[]>(
  "activeTrades/loadActiveTrades",
  async (_, thunkAPI) =>
    await handleThunkError(thunkAPI, traderRestApi.getActiveTrades())
);

export const activeTradesSlice = createSlice({
  name: "activeTrades",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    setActiveTrades: (state, { payload }: PayloadAction<ActiveTrade[]>) => {
      state.activeTrades = payload;
    },
    setSelectedActiveTrade: (
      state,
      { payload }: PayloadAction<ActiveTrade>
    ) => {
      state.selected = payload;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere, including actions generated by createAsyncThunk or in other slices.
  extraReducers: {
    [loadActiveTrades.pending as any]: (state: ActiveTradesState) => {
      state.activeTrades = [];
      state.activeTradesLoading = LoadingState.LOADING;
    },
    [loadActiveTrades.fulfilled as any]: (
      state: ActiveTradesState,
      action: PayloadAction<ActiveTrade[]>
    ) => {
      state.activeTrades = action.payload;
      state.activeTradesLoading = LoadingState.LOADED;
    },
    [loadActiveTrades.rejected as any]: (
      state: ActiveTradesState,
      action: PayloadAction<any>
    ) => {
      state.activeTradesLoadingError = action.payload;
      state.activeTradesLoading = LoadingState.ERROR;
    },
  },
});

export const {
  setActiveTrades,
  setSelectedActiveTrade,
} = activeTradesSlice.actions;

export const selectActiveTrades = createSelector(
  (state: RootState) => ({
    activeTrades: state.activeTrades.activeTrades,
    activeTradesLoading: state.activeTrades.activeTradesLoading,
    activeTradesLoadingError: state.activeTrades.activeTradesLoadingError,

    selected: state.activeTrades.selected,
  }),
  (state) => state
);

export default activeTradesSlice.reducer;
